#!/bin/bash
# Restore the SecretsBuiltin.xojo_code stub after a manual IDE build.
# Run this immediately after the build completes.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILTIN="$SCRIPT_DIR/src/SecretsBuiltin.xojo_code"

cat > "$BUILTIN" << 'STUB'
#tag Module
Protected Module SecretsBuiltin
	#tag Method, Flags = &h0
		Function Get(account As String) As String
		  ' Generated by inject-secrets.sh — do not edit. See Secrets.xojo_code.
		  #Pragma Unused account
		  Return ""
		End Function
	#tag EndMethod

End Module
#tag EndModule
STUB

echo "✓ SecretsBuiltin.xojo_code restored to stub. Safe to commit."
