#tag Module
Protected Module SecretsBuiltin
	#tag Method, Flags = &h0
		Function Get(account As String) As String
		  ' Generated by inject-secrets.sh — do not edit. See Secrets.xojo_code.
		  #Pragma Unused account
		  Return ""
		End Function
	#tag EndMethod

End Module
#tag EndModule
